extends: airbnb
parser: babel-eslint
env:
  browser: true
rules:
  react/jsx-filename-extension: [error, { extensions: [.js, .jsx] }]
  import/prefer-default-export: off
  no-underscore-dangle: off
  comma-dangle: ["error", "never"]
